language: c
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env:
        - EXEC="qemu-mips"
      install:
        - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"
        - sudo apt-get -qq update
        - sudo apt-get install gcc-mips-linux-gnu qemu-user
        - mips-linux-gnu-gcc --version
        - qemu-mips -version

script:
  - make -C build/linux/make/ clean
  - make -C build/linux/make/ CONFIG=release_64_static build
