language: c
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=mips-unknown-linux-gnu
      apt:
        sources:
          - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial main universe"
        packages:
          - gcc-mips-linux-gnu
          - libc6-dev-mips-cross
          - qemu-user-binfmt

script:
  - make -C build/linux/make/ clean
  - make -C build/linux/make/ CONFIG=release_64_static build
