language: c
compiler: gcc
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=mips-unknown-linux-gnu

script:
  - make -C build/linux/make/ clean
  - make -C build/linux/make/ CONFIG=release_64_static build
